In [5]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("data/raw")

def load_csv(filename):
    return pd.read_csv(
        DATA_PATH / filename,
        sep=";",
        encoding="utf-8"
    )

orders = load_csv("Ir4_wc_order_stats.csv")
customers = load_csv("Ir4_wc_customer_lookup.csv")
order_items = load_csv("Ir4_woocommerce_order_items.csv")
order_itemmeta = load_csv("Ir4_woocommerce_order_itemmeta.csv")
products = load_csv("Ir4_wc_product_meta_lookup.csv")
coupons = load_csv("Ir4_wc_order_coupon_lookup.csv")
discounts = load_csv("Ir4_wdr_order_item_discounts.csv")
posts = load_csv("Ir4_posts.csv")
postmeta = load_csv("Ir4_postmeta.csv")

In [6]:
datasets = {
    "Orders": orders,
    "Customers": customers,
    "Order Items": order_items,
    "Order Item Meta": order_itemmeta,
    "Products": products,
    "Coupons": coupons,
    "Discounts": discounts,
    "Posts": posts,
    "Post Meta": postmeta
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * 50)
    print(df.shape)

Orders
--------------------------------------------------
(18043, 14)

Customers
--------------------------------------------------
(56213, 12)

Order Items
--------------------------------------------------
(47294, 4)

Order Item Meta
--------------------------------------------------
(521678, 4)

Products
--------------------------------------------------
(11002, 14)

Coupons
--------------------------------------------------
(3280, 4)

Discounts
--------------------------------------------------
(95, 20)

Posts
--------------------------------------------------
(29277, 23)

Post Meta
--------------------------------------------------
(1236208, 4)

In [7]:
datasets = {
    "Orders": orders,
    "Customers": customers,
    "Order Items": order_items,
    "Order Item Meta": order_itemmeta,
    "Products": products,
    "Coupons": coupons,
    "Discounts": discounts,
    "Posts": posts,
    "Post Meta": postmeta
}

for name, df in datasets.items():
    print("=" * 70)
    print(f"📊 {name}")
    print("=" * 70)
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    print("\n")

======================================================================
📊 Orders
======================================================================
Shape: (18043, 14)

Columns:
['order_id', 'parent_id', 'date_created', 'date_created_gmt', 'num_items_sold', 'total_sales', 'tax_total', 'shipping_total', 'net_total', 'returning_customer', 'status', 'customer_id', 'date_paid', 'date_completed']


======================================================================
📊 Customers
======================================================================
Shape: (56213, 12)

Columns:
['customer_id', 'user_id', 'username', 'first_name', 'last_name', 'email', 'date_last_active', 'date_registered', 'country', 'postcode', 'city', 'state']


======================================================================
📊 Order Items
======================================================================
Shape: (47294, 4)

Columns:
['order_item_id', 'order_item_name', 'order_item_type', 'order_id']


======================================================================
📊 Order Item Meta
======================================================================
Shape: (521678, 4)

Columns:
['meta_id', 'order_item_id', 'meta_key', 'meta_value']


======================================================================
📊 Products
======================================================================
Shape: (11002, 14)

Columns:
['product_id', 'sku', 'virtual', 'downloadable', 'min_price', 'max_price', 'onsale', 'stock_quantity', 'stock_status', 'rating_count', 'average_rating', 'total_sales', 'tax_status', 'tax_class']


======================================================================
📊 Coupons
======================================================================
Shape: (3280, 4)

Columns:
['order_id', 'coupon_id', 'date_created', 'discount_amount']


======================================================================
📊 Discounts
======================================================================
Shape: (95, 20)

Columns:
['id', 'order_id', 'order_item_id', 'rule_id', 'item_id', 'item_price', 'discounted_price', 'discount', 'quantity', 'simple_discount', 'bulk_discount', 'set_discount', 'cart_discount', 'other_discount', 'has_free_shipping', 'cart_discount_label', 'other_price', 'created_at', 'updated_at', 'extra']


======================================================================
📊 Posts
======================================================================
Shape: (29277, 23)

Columns:
['ID', 'post_author', 'post_date', 'post_date_gmt', 'post_content', 'post_title', 'post_excerpt', 'post_status', 'comment_status', 'ping_status', 'post_password', 'post_name', 'to_ping', 'pinged', 'post_modified', 'post_modified_gmt', 'post_content_filtered', 'post_parent', 'guid', 'menu_order', 'post_type', 'post_mime_type', 'comment_count']


======================================================================
📊 Post Meta
======================================================================
Shape: (1236208, 4)

Columns:
['meta_id', 'post_id', 'meta_key', 'meta_value']

In [8]:
for name, df in datasets.items():
    print("=" * 70)
    print(name)
    print("=" * 70)
    print(df.dtypes)
    print()

======================================================================
Orders
======================================================================
order_id                int64
parent_id               int64
date_created           object
date_created_gmt       object
num_items_sold          int64
total_sales           float64
tax_total               int64
shipping_total          int64
net_total             float64
returning_customer    float64
status                 object
customer_id             int64
date_paid              object
date_completed         object
dtype: object

======================================================================
Customers
======================================================================
customer_id           int64
user_id             float64
username             object
first_name           object
last_name            object
email                object
date_last_active     object
date_registered      object
country              object
postcode             object
city                 object
state                object
dtype: object

======================================================================
Order Items
======================================================================
order_item_id       int64
order_item_name    object
order_item_type    object
order_id            int64
dtype: object

======================================================================
Order Item Meta
======================================================================
meta_id           int64
order_item_id     int64
meta_key         object
meta_value       object
dtype: object

======================================================================
Products
======================================================================
product_id          int64
sku                object
virtual             int64
downloadable        int64
min_price         float64
max_price         float64
onsale              int64
stock_quantity    float64
stock_status       object
rating_count        int64
average_rating    float64
total_sales         int64
tax_status         object
tax_class          object
dtype: object

======================================================================
Coupons
======================================================================
order_id             int64
coupon_id            int64
date_created        object
discount_amount    float64
dtype: object

======================================================================
Discounts
======================================================================
id                       int64
order_id                 int64
order_item_id            int64
rule_id                  int64
item_id                  int64
item_price               int64
discounted_price         int64
discount                 int64
quantity                 int64
simple_discount          int64
bulk_discount            int64
set_discount             int64
cart_discount          float64
other_discount           int64
has_free_shipping       object
cart_discount_label     object
other_price              int64
created_at              object
updated_at              object
extra                  float64
dtype: object

======================================================================
Posts
======================================================================
ID                         int64
post_author                int64
post_date                 object
post_date_gmt             object
post_content              object
post_title                object
post_excerpt              object
post_status               object
comment_status            object
ping_status               object
post_password             object
post_name                 object
to_ping                  float64
pinged                   float64
post_modified             object
post_modified_gmt         object
post_content_filtered    float64
post_parent                int64
guid                      object
menu_order                 int64
post_type                 object
post_mime_type            object
comment_count              int64
dtype: object

======================================================================
Post Meta
======================================================================
meta_id        int64
post_id        int64
meta_key      object
meta_value    object
dtype: object

In [9]:
for name, df in datasets.items():
    print("=" * 70)
    print(name)
    print("=" * 70)
    print(df.isnull().sum())
    print()

======================================================================
Orders
======================================================================
order_id                 0
parent_id                0
date_created             0
date_created_gmt         0
num_items_sold           0
total_sales              0
tax_total                0
shipping_total           0
net_total                0
returning_customer     602
status                   0
customer_id              0
date_paid             2078
date_completed        2465
dtype: int64

======================================================================
Customers
======================================================================
customer_id             0
user_id               529
username              529
first_name          40992
last_name           40992
email                   3
date_last_active    37303
date_registered       529
country             41102
postcode            41107
city                41105
state               41119
dtype: int64

======================================================================
Order Items
======================================================================
order_item_id      0
order_item_name    0
order_item_type    0
order_id           0
dtype: int64

======================================================================
Order Item Meta
======================================================================
meta_id              0
order_item_id        0
meta_key             0
meta_value       40018
dtype: int64

======================================================================
Products
======================================================================
product_id            0
sku               11001
virtual               0
downloadable          0
min_price             0
max_price             0
onsale                0
stock_quantity    10616
stock_status          0
rating_count          0
average_rating        0
total_sales           0
tax_status            0
tax_class           835
dtype: int64

======================================================================
Coupons
======================================================================
order_id           0
coupon_id          0
date_created       0
discount_amount    0
dtype: int64

======================================================================
Discounts
======================================================================
id                      0
order_id                0
order_item_id           0
rule_id                 0
item_id                 0
item_price              0
discounted_price        0
discount                0
quantity                0
simple_discount         0
bulk_discount           0
set_discount            0
cart_discount           0
other_discount          0
has_free_shipping       0
cart_discount_label     0
other_price             0
created_at              0
updated_at              0
extra                  95
dtype: int64

======================================================================
Posts
======================================================================
ID                           0
post_author                  0
post_date                    0
post_date_gmt                0
post_content             26443
post_title                  53
post_excerpt             16845
post_status                  0
comment_status               0
ping_status                  0
post_password            12393
post_name                    1
to_ping                  29277
pinged                   29277
post_modified                0
post_modified_gmt            0
post_content_filtered    29277
post_parent                  0
guid                         1
menu_order                   0
post_type                    0
post_mime_type           26553
comment_count                0
dtype: int64

======================================================================
Post Meta
======================================================================
meta_id           0
post_id           0
meta_key          0
meta_value    27051
dtype: int64

In [10]:
for key in datasets:
    datasets[key] = datasets[key].drop_duplicates()

In [11]:
for name, df in datasets.items():
    print(name, df.shape)

Orders (18043, 14)
Customers (56213, 12)
Order Items (47294, 4)
Order Item Meta (521678, 4)
Products (11002, 14)
Coupons (3280, 4)
Discounts (95, 20)
Posts (29277, 23)
Post Meta (1236208, 4)

In [12]:
from pathlib import Path

processed_path = Path("data/processed")
processed_path.mkdir(exist_ok=True)

for name, df in datasets.items():
    filename = name.lower().replace(" ", "_") + ".csv"
    df.to_csv(processed_path / filename, index=False)

In [13]:
order_itemmeta.head(20)

,meta_id,order_item_id,meta_key,meta_value
0,1,1,_product_id,77
1,2,1,_variation_id,90
2,3,1,_qty,1
3,4,1,_tax_class,NaN
4,5,1,_line_subtotal,72
5,6,1,_line_subtotal_tax,0
6,7,1,_line_total,72
7,8,1,_line_tax,0
8,9,1,_line_tax_data,"a:2:{s:5:""total"";a:0:{}s:8:""subtotal"";a:0:{}}"
9,10,1,pa_color,light-blue2
10,11,1,_ywapo_meta_data,"a:1:{i:0;a:1:{s:3:""2-0"";s:0:"""";}}"
11,12,2,method_id,flat_rate
12,13,2,instance_id,2
13,14,2,cost,100
14,15,2,total_tax,0
15,16,2,taxes,"a:1:{s:5:""total"";a:0:{}}"
16,17,2,Items,Finlay Xs Backpack &times; 1
17,18,3,_product_id,74
18,19,3,_variation_id,0
19,20,3,_qty,1

In [14]:
order_itemmeta['meta_key'].value_counts().head(30)

meta_key
_tax_class                                        26647
_line_total                                       26647
_line_tax                                         26647
_line_tax_data                                    26647
_qty                                              26555
_line_subtotal                                    26555
_line_subtotal_tax                                26555
_product_id                                       26554
_variation_id                                     26554
pa_size                                           26517
_ywapo_meta_data                                  26037
Order Note: Please enter your height in ft/cm.    20683
method_id                                         16759
instance_id                                       16759
cost                                              16759
total_tax                                         16759
taxes                                             16759
Items                                             16756
Points                                            14718
_fs_method                                        13454
_default                                          13454
_fs_integration                                   13454
description                                       13454
Option                                             7747
_reduced_stock                                     6182
discount_amount_tax                                3888
discount_amount                                    3888
ywapo-addon-2-0                                    3804
coupon_data                                        3316
pa_color                                           3230
Name: count, dtype: int64

In [15]:
posts['post_type'].value_counts()

post_type
shop_order           16302
product_variation     6612
attachment            2724
shop_coupon           2003
shop_order_refund      587
product                511
nav_menu_item          206
postman_sent_mail      201
page                    63
post                    17
fmtpl_blocks             8
popup_theme              8
portfolio                6
elementor_library        6
custom_css               4
lws-wre-event            4
popup                    3
feedback                 3
mc4wp-form               2
order_status             2
mailpoet_page            1
wp_global_styles         1
aoc_popup                1
wpforms                  1
lws-wre-pool             1
Name: count, dtype: int64

In [16]:
posts[posts['post_type']=="product"][['ID','post_title']].head()

       ID                     post_title
167  1268       Lavender georgette dress
177  1278    Pastel blue georgette dress
187  1289         Maroon georgette dress
197  1311  Grey high low georgette dress
207  1328           Black cotton dress 3

In [17]:
orders.head()

,order_id,parent_id,date_created,date_created_gmt,num_items_sold,total_sales,tax_total,shipping_total,net_total,returning_customer,status,customer_id,date_paid,date_completed
0,216,0,2022-03-13 17:12:55,2022-03-13 17:12:55,1,172.0,0,100,72.0,1.0,wc-trash,1,0000-00-00 00:00:00,0000-00-00 00:00:00
1,217,0,2022-03-13 17:16:02,2022-03-13 17:16:02,1,190.0,0,100,90.0,1.0,wc-trash,1,0000-00-00 00:00:00,0000-00-00 00:00:00
2,2199,0,2022-03-14 09:44:17,2022-03-14 09:44:17,1,1500.0,0,100,1400.0,0.0,wc-completed,1,2022-03-14 03:45:06,2022-04-13 20:45:54
3,2642,0,2022-03-14 13:45:18,2022-03-14 13:45:18,1,1700.0,0,100,1600.0,0.0,wc-trash,2,0000-00-00 00:00:00,0000-00-00 00:00:00
4,2643,0,2022-03-14 13:48:14,2022-03-14 13:48:14,1,1550.0,0,100,1450.0,0.0,wc-trash,3,0000-00-00 00:00:00,0000-00-00 00:00:00

In [18]:
orders.describe(include="all")

,order_id,parent_id,date_created,date_created_gmt,num_items_sold,total_sales,tax_total,shipping_total,net_total,returning_customer,status,customer_id,date_paid,date_completed
count,18043.000000,18043.000000,18043,18043,18043.000000,18043.000000,18043.0,18043.000000,18043.000000,17441.000000,18043,18043.000000,15965,15578
unique,NaN,NaN,18031,18031,NaN,NaN,NaN,NaN,NaN,NaN,9,NaN,14375,12214
top,NaN,NaN,2024-02-26 19:54:16,2024-02-26 19:54:16,NaN,NaN,NaN,NaN,NaN,NaN,wc-completed,NaN,0000-00-00 00:00:00,0000-00-00 00:00:00
freq,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,13941,NaN,1582,1679
mean,21931.223632,484.744832,NaN,NaN,1.472316,2535.254944,0.0,142.651832,2392.603113,0.116106,NaN,17352.792385,NaN,NaN
std,12641.321834,3492.007334,NaN,NaN,1.215841,2287.043705,0.0,410.790197,2137.655165,0.320361,NaN,17492.818096,NaN,NaN
min,216.000000,0.000000,NaN,NaN,0.000000,-12350.000000,0.0,0.000000,-12350.000000,0.000000,NaN,0.000000,NaN,NaN
25%,9702.500000,0.000000,NaN,NaN,1.000000,1650.000000,0.0,100.000000,1582.000000,0.000000,NaN,4116.500000,NaN,NaN
50%,21850.000000,0.000000,NaN,NaN,1.000000,1850.000000,0.0,100.000000,1750.000000,0.000000,NaN,10051.000000,NaN,NaN
75%,33977.000000,0.000000,NaN,NaN,2.000000,3050.000000,0.0,100.000000,2950.000000,0.000000,NaN,28477.500000,NaN,NaN
max,42672.000000,41209.000000,NaN,NaN,19.000000,34160.000000,0.0,6680.000000,30606.000000,1.000000,NaN,59233.000000,NaN,NaN

In [19]:
order_itemmeta['meta_key'].value_counts().head(30)

meta_key
_tax_class                                        26647
_line_total                                       26647
_line_tax                                         26647
_line_tax_data                                    26647
_qty                                              26555
_line_subtotal                                    26555
_line_subtotal_tax                                26555
_product_id                                       26554
_variation_id                                     26554
pa_size                                           26517
_ywapo_meta_data                                  26037
Order Note: Please enter your height in ft/cm.    20683
method_id                                         16759
instance_id                                       16759
cost                                              16759
total_tax                                         16759
taxes                                             16759
Items                                             16756
Points                                            14718
_fs_method                                        13454
_default                                          13454
_fs_integration                                   13454
description                                       13454
Option                                             7747
_reduced_stock                                     6182
discount_amount_tax                                3888
discount_amount                                    3888
ywapo-addon-2-0                                    3804
coupon_data                                        3316
pa_color                                           3230
Name: count, dtype: int64

In [20]:
order_itemmeta.head(20)

,meta_id,order_item_id,meta_key,meta_value
0,1,1,_product_id,77
1,2,1,_variation_id,90
2,3,1,_qty,1
3,4,1,_tax_class,NaN
4,5,1,_line_subtotal,72
5,6,1,_line_subtotal_tax,0
6,7,1,_line_total,72
7,8,1,_line_tax,0
8,9,1,_line_tax_data,"a:2:{s:5:""total"";a:0:{}s:8:""subtotal"";a:0:{}}"
9,10,1,pa_color,light-blue2
10,11,1,_ywapo_meta_data,"a:1:{i:0;a:1:{s:3:""2-0"";s:0:"""";}}"
11,12,2,method_id,flat_rate
12,13,2,instance_id,2
13,14,2,cost,100
14,15,2,total_tax,0
15,16,2,taxes,"a:1:{s:5:""total"";a:0:{}}"
16,17,2,Items,Finlay Xs Backpack &times; 1
17,18,3,_product_id,74
18,19,3,_variation_id,0
19,20,3,_qty,1

In [21]:
posts['post_type'].value_counts()

post_type
shop_order           16302
product_variation     6612
attachment            2724
shop_coupon           2003
shop_order_refund      587
product                511
nav_menu_item          206
postman_sent_mail      201
page                    63
post                    17
fmtpl_blocks             8
popup_theme              8
portfolio                6
elementor_library        6
custom_css               4
lws-wre-event            4
popup                    3
feedback                 3
mc4wp-form               2
order_status             2
mailpoet_page            1
wp_global_styles         1
aoc_popup                1
wpforms                  1
lws-wre-pool             1
Name: count, dtype: int64

In [22]:
posts[posts['post_type']=="product"][['ID','post_title']].head()

       ID                     post_title
167  1268       Lavender georgette dress
177  1278    Pastel blue georgette dress
187  1289         Maroon georgette dress
197  1311  Grey high low georgette dress
207  1328           Black cotton dress 3