In [1]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/raw")

In [2]:
def load_csv(filename):
    return pd.read_csv(
        DATA_PATH / filename,
        sep=";",
        encoding="utf-8"
    )

In [3]:
orders = load_csv("Ir4_wc_order_stats.csv")
customers = load_csv("Ir4_wc_customer_lookup.csv")
order_items = load_csv("Ir4_woocommerce_order_items.csv")
order_itemmeta = load_csv("Ir4_woocommerce_order_itemmeta.csv")
products = load_csv("Ir4_wc_product_meta_lookup.csv")
coupons = load_csv("Ir4_wc_order_coupon_lookup.csv")
discounts = load_csv("Ir4_wdr_order_item_discounts.csv")
posts = load_csv("Ir4_posts.csv")
postmeta = load_csv("Ir4_postmeta.csv")

In [4]:
order_itemmeta.head()

   meta_id  order_item_id        meta_key meta_value
0        1              1     _product_id         77
1        2              1   _variation_id         90
2        3              1            _qty          1
3        4              1      _tax_class        NaN
4        5              1  _line_subtotal         72

In [5]:
pivot_meta = (
    order_itemmeta
    .pivot_table(
        index='order_item_id',
        columns='meta_key',
        values='meta_value',
        aggfunc='first'
    )
    .reset_index()
)

pivot_meta.head()

meta_key,order_item_id,Back Zip.,Calf Length Dress,Duppatta,Feeding zips.,Full length dress.,Items,Lining,Option,Order Note: Please enter your height in ft/cm.,...,ywapo-addon-1-1,ywapo-addon-1-2,ywapo-addon-10-0,ywapo-addon-12-0,ywapo-addon-13-0,ywapo-addon-2-0,ywapo-addon-4-0,ywapo-addon-6-0,ywapo-addon-7-0,ywapo-addon-8-0
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,NaN,Finlay Xs Backpack &times; 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,The Washable Silk Henley Tank &times; 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
order_itemmeta.head()

   meta_id  order_item_id        meta_key meta_value
0        1              1     _product_id         77
1        2              1   _variation_id         90
2        3              1            _qty          1
3        4              1      _tax_class        NaN
4        5              1  _line_subtotal         72

In [7]:
pivot_meta.head()

meta_key,order_item_id,Back Zip.,Calf Length Dress,Duppatta,Feeding zips.,Full length dress.,Items,Lining,Option,Order Note: Please enter your height in ft/cm.,...,ywapo-addon-1-1,ywapo-addon-1-2,ywapo-addon-10-0,ywapo-addon-12-0,ywapo-addon-13-0,ywapo-addon-2-0,ywapo-addon-4-0,ywapo-addon-6-0,ywapo-addon-7-0,ywapo-addon-8-0
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,NaN,Finlay Xs Backpack &times; 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,The Washable Silk Henley Tank &times; 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pivot_meta.columns.tolist()

['order_item_id',
 'Back Zip.',
 'Calf Length Dress',
 'Duppatta',
 'Feeding zips. ',
 'Full length dress.',
 'Items',
 'Lining',
 'Option',
 'Order Note: Please enter your height in ft/cm.',
 'Points',
 'Scallop neckline',
 'Sleeve Customisation',
 '_advanced_woo_discount_item_total_discount',
 '_default',
 '_fee_amount',
 '_fs_integration',
 '_fs_method',
 '_line_subtotal',
 '_line_subtotal_tax',
 '_line_tax',
 '_line_tax_data',
 '_line_total',
 '_nrp_points',
 '_nrp_quantity',
 '_ppom_fields',
 '_product_id',
 '_qty',
 '_reduced_stock',
 '_tax_class',
 '_tax_status',
 '_variation_id',
 '_wdr_discounts',
 '_ywapo_meta_data',
 'back_zip',
 'calf_length_dress_',
 'cost',
 'coupon_data',
 'coupon_info',
 'discount_amount',
 'discount_amount_tax',
 'f_feeding_zips_',
 'f_scallop_neckline',
 'full_length_dress',
 'instance_id',
 'method_id',
 'order_note__please_enter_your_height_in_ft_cm___',
 'pa_color',
 'pa_fabric-image',
 'pa_size',
 'shipping',
 'sleeve_customisation',
 'taxes',
 'total_tax',
 'ywapo-addon-1-0',
 'ywapo-addon-1-1',
 'ywapo-addon-1-2',
 'ywapo-addon-10-0',
 'ywapo-addon-12-0',
 'ywapo-addon-13-0',
 'ywapo-addon-2-0',
 'ywapo-addon-4-0',
 'ywapo-addon-6-0',
 'ywapo-addon-7-0',
 'ywapo-addon-8-0']

In [9]:
important_columns = [
    'order_item_id',
    '_product_id',
    '_qty',
    '_line_total',
    '_line_subtotal',
    '_line_tax',
    '_variation_id'
]

pivot_meta = pivot_meta[important_columns]

pivot_meta.head()

meta_key,order_item_id,_product_id,_qty,_line_total,_line_subtotal,_line_tax,_variation_id
0,1,77,1,72,72,0,90
1,2,NaN,NaN,NaN,NaN,NaN,NaN
2,3,74,1,90,90,0,0
3,4,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1328,1,1400,1400,0,1332

In [10]:
pivot_meta.rename(columns={
    '_product_id': 'product_id',
    '_qty': 'quantity',
    '_line_total': 'line_total',
    '_line_subtotal': 'subtotal',
    '_line_tax': 'tax',
    '_variation_id': 'variation_id'
}, inplace=True)

In [11]:
numeric_cols = [
    'product_id',
    'quantity',
    'line_total',
    'subtotal',
    'tax',
    'variation_id'
]

for col in numeric_cols:
    pivot_meta[col] = pd.to_numeric(
        pivot_meta[col],
        errors='coerce'
    )

In [12]:
pivot_meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47294 entries, 0 to 47293
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  47294 non-null  int64
 1   product_id     26554 non-null  float64
 2   quantity       26555 non-null  float64
 3   line_total     26647 non-null  float64
 4   subtotal       26555 non-null  float64
 5   tax            26647 non-null  float64
 6   variation_id   26554 non-null  float64
dtypes: float64(6), int64(1)
memory usage: 2.5 MB

In [13]:
order_details = order_items.merge(
    pivot_meta,
    on='order_item_id',
    how='left'
)

order_details.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0
1,2,DELIVERY CHARGES,shipping,216,NaN,NaN,NaN,NaN,NaN,NaN
2,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0
3,4,DELIVERY CHARGES,shipping,217,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0

In [14]:
pivot_meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47294 entries, 0 to 47293
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  47294 non-null  int64
 1   product_id     26554 non-null  float64
 2   quantity       26555 non-null  float64
 3   line_total     26647 non-null  float64
 4   subtotal       26555 non-null  float64
 5   tax            26647 non-null  float64
 6   variation_id   26554 non-null  float64
dtypes: float64(6), int64(1)
memory usage: 2.5 MB

In [15]:
order_details = order_details[
    order_details['order_item_type'] == 'line_item'
].copy()

order_details.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0
2,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0
4,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0
6,7,Baby pink 2 tier cotton dress - XXS,line_item,2642,2381.0,1.0,1600.0,1600.0,0.0,2382.0
8,9,Black cotton dress 3 - M,line_item,2643,1328.0,1.0,1450.0,1450.0,0.0,1332.0

In [16]:
order_details.shape

(26554, 10)

In [17]:
master = order_details.merge(
    orders,
    on='order_id',
    how='left'
)

master.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id,...,num_items_sold,total_sales,tax_total,shipping_total,net_total,returning_customer,status,customer_id,date_paid,date_completed
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0,...,1.0,172.0,0.0,100.0,72.0,1.0,wc-trash,1.0,0000-00-00 00:00:00,0000-00-00 00:00:00
1,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0,...,1.0,190.0,0.0,100.0,90.0,1.0,wc-trash,1.0,0000-00-00 00:00:00,0000-00-00 00:00:00
2,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0,...,1.0,1500.0,0.0,100.0,1400.0,0.0,wc-completed,1.0,2022-03-14 03:45:06,2022-04-13 20:45:54
3,7,Baby pink 2 tier cotton dress - XXS,line_item,2642,2381.0,1.0,1600.0,1600.0,0.0,2382.0,...,1.0,1700.0,0.0,100.0,1600.0,0.0,wc-trash,2.0,0000-00-00 00:00:00,0000-00-00 00:00:00
4,9,Black cotton dress 3 - M,line_item,2643,1328.0,1.0,1450.0,1450.0,0.0,1332.0,...,1.0,1550.0,0.0,100.0,1450.0,0.0,wc-trash,3.0,0000-00-00 00:00:00,0000-00-00 00:00:00

In [18]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26554 entries, 0 to 26553
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_item_id       26554 non-null  int64
 1   order_item_name     26554 non-null  object
 2   order_item_type     26554 non-null  object
 3   order_id            26554 non-null  int64
 4   product_id          26554 non-null  float64
 5   quantity            26554 non-null  float64
 6   line_total          26554 non-null  float64
 7   subtotal            26554 non-null  float64
 8   tax                 26554 non-null  float64
 9   variation_id        26554 non-null  float64
 10  parent_id           26516 non-null  float64
 11  date_created        26516 non-null  object
 12  date_created_gmt    26516 non-null  object
 13  num_items_sold      26516 non-null  float64
 14  total_sales         26516 non-null  float64
 15  tax_total           26516 non-null  float64
 16  shipping_total      26516 non-null  float64
 17  net_total           26516 non-null  float64
 18  returning_customer  26516 non-null  float64
 19  status              26516 non-null  object
 20  customer_id         26516 non-null  float64
 21  date_paid           23022 non-null  object
 22  date_completed      22375 non-null  object
dtypes: float64(14), int64(2), object(7)
memory usage: 4.7+ MB

In [19]:
master = master.merge(
    customers,
    on='customer_id',
    how='left'
)

master.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id,...,username,first_name,last_name,email,date_last_active,date_registered,country,postcode,city,state
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0,...,meghana,meghana,sharma,noreply@thehandloomproject.in,2024-07-20 10:08:45,2022-03-12 17:08:16,IN,500017,Hyderabad,AP
1,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0,...,meghana,meghana,sharma,noreply@thehandloomproject.in,2024-07-20 10:08:45,2022-03-12 17:08:16,IN,500017,Hyderabad,AP
2,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0,...,meghana,meghana,sharma,noreply@thehandloomproject.in,2024-07-20 10:08:45,2022-03-12 17:08:16,IN,500017,Hyderabad,AP
3,7,Baby pink 2 tier cotton dress - XXS,line_item,2642,2381.0,1.0,1600.0,1600.0,0.0,2382.0,...,rajendra.raj,Rajendra,Raj,rajendra.7120@gmail.com,2023-04-11 00:00:00,2022-03-14 13:45:18,IN,560043,bangalore,KA
4,9,Black cotton dress 3 - M,line_item,2643,1328.0,1.0,1450.0,1450.0,0.0,1332.0,...,NaN,Meghana,Naidu,chepena.meghananaidu@gmail.com,2022-03-14 13:48:14,NaN,IN,500055,Hyderabad,TS

In [20]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26554 entries, 0 to 26553
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_item_id       26554 non-null  int64
 1   order_item_name     26554 non-null  object
 2   order_item_type     26554 non-null  object
 3   order_id            26554 non-null  int64
 4   product_id          26554 non-null  float64
 5   quantity            26554 non-null  float64
 6   line_total          26554 non-null  float64
 7   subtotal            26554 non-null  float64
 8   tax                 26554 non-null  float64
 9   variation_id        26554 non-null  float64
 10  parent_id           26516 non-null  float64
 11  date_created        26516 non-null  object
 12  date_created_gmt    26516 non-null  object
 13  num_items_sold      26516 non-null  float64
 14  total_sales         26516 non-null  float64
 15  tax_total           26516 non-null  float64
 16  shipping_total      26516 non-null  float64
 17  net_total           26516 non-null  float64
 18  returning_customer  26516 non-null  float64
 19  status              26516 non-null  object
 20  customer_id         26516 non-null  float64
 21  date_paid           23022 non-null  object
 22  date_completed      22375 non-null  object
 23  user_id             25617 non-null  float64
 24  username            25617 non-null  object
 25  first_name          26496 non-null  object
 26  last_name           26496 non-null  object
 27  email               26496 non-null  object
 28  date_last_active    26483 non-null  object
 29  date_registered     25617 non-null  object
 30  country             26483 non-null  object
 31  postcode            26470 non-null  object
 32  city                26480 non-null  object
 33  state               26439 non-null  object
dtypes: float64(15), int64(2), object(17)
memory usage: 6.9+ MB

In [21]:
master = master.merge(
    products,
    on='product_id',
    how='left'
)

master.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id,...,min_price,max_price,onsale,stock_quantity,stock_status,rating_count,average_rating,total_sales_y,tax_status,tax_class
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0,...,1100.0,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN
3,7,Baby pink 2 tier cotton dress - XXS,line_item,2642,2381.0,1.0,1600.0,1600.0,0.0,2382.0,...,1250.0,1550.0,0.0,NaN,instock,1.0,5.0,198.0,taxable,NaN
4,9,Black cotton dress 3 - M,line_item,2643,1328.0,1.0,1450.0,1450.0,0.0,1332.0,...,1100.0,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN

In [22]:
product_names = (
    posts[posts['post_type'] == 'product']
    [['ID', 'post_title']]
    .rename(columns={
        'ID': 'product_id',
        'post_title': 'product_name'
    })
)

product_names.head()

     product_id                   product_name
167        1268       Lavender georgette dress
177        1278    Pastel blue georgette dress
187        1289         Maroon georgette dress
197        1311  Grey high low georgette dress
207        1328           Black cotton dress 3

In [23]:
product_names['product_id'] = pd.to_numeric(
    product_names['product_id'],
    errors='coerce'
)

In [24]:
master = master.merge(
    product_names,
    on='product_id',
    how='left'
)

master.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id,...,max_price,onsale,stock_quantity,stock_status,rating_count,average_rating,total_sales_y,tax_status,tax_class,product_name
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0,...,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN,Black cotton dress 3
3,7,Baby pink 2 tier cotton dress - XXS,line_item,2642,2381.0,1.0,1600.0,1600.0,0.0,2382.0,...,1550.0,0.0,NaN,instock,1.0,5.0,198.0,taxable,NaN,Baby pink 2 tier cotton dress
4,9,Black cotton dress 3 - M,line_item,2643,1328.0,1.0,1450.0,1450.0,0.0,1332.0,...,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN,Black cotton dress 3

In [25]:
master.shape

(26554, 48)

In [26]:
master.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id,...,max_price,onsale,stock_quantity,stock_status,rating_count,average_rating,total_sales_y,tax_status,tax_class,product_name
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0,...,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN,Black cotton dress 3
3,7,Baby pink 2 tier cotton dress - XXS,line_item,2642,2381.0,1.0,1600.0,1600.0,0.0,2382.0,...,1550.0,0.0,NaN,instock,1.0,5.0,198.0,taxable,NaN,Baby pink 2 tier cotton dress
4,9,Black cotton dress 3 - M,line_item,2643,1328.0,1.0,1450.0,1450.0,0.0,1332.0,...,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN,Black cotton dress 3

In [27]:
master.to_csv("../data/processed/master_dataset.csv", index=False)

In [28]:
master.head()

,order_item_id,order_item_name,order_item_type,order_id,product_id,quantity,line_total,subtotal,tax,variation_id,...,max_price,onsale,stock_quantity,stock_status,rating_count,average_rating,total_sales_y,tax_status,tax_class,product_name
0,1,Finlay Xs Backpack,line_item,216,77.0,1.0,72.0,72.0,0.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,The Washable Silk Henley Tank,line_item,217,74.0,1.0,90.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Black cotton dress 3 - M,line_item,2199,1328.0,1.0,1400.0,1400.0,0.0,1332.0,...,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN,Black cotton dress 3
3,7,Baby pink 2 tier cotton dress - XXS,line_item,2642,2381.0,1.0,1600.0,1600.0,0.0,2382.0,...,1550.0,0.0,NaN,instock,1.0,5.0,198.0,taxable,NaN,Baby pink 2 tier cotton dress
4,9,Black cotton dress 3 - M,line_item,2643,1328.0,1.0,1450.0,1450.0,0.0,1332.0,...,1400.0,0.0,NaN,instock,1.0,5.0,1009.0,taxable,NaN,Black cotton dress 3

In [29]:
from pathlib import Path

output = Path("../data/processed")
output.mkdir(parents=True, exist_ok=True)

master.to_csv(output / "master_dataset.csv", index=False)

print("✅ Saved successfully!")

✅ Saved successfully!